"""Initial migration with Company, TechSignal, and AIReadinessScore models

Revision ID: 32c4c0140d40
Revises: 
Create Date: 2025-08-19 22:41:26.221502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32c4c0140d40'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('size_category', sa.Enum('STARTUP', 'SMB', 'ENTERPRISE', name='companysizecategory'), nullable=True),
    sa.Column('headquarters', sa.String(length=255), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('revenue_range', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_domain'), 'companies', ['domain'], unique=True)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('ai_readiness_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('component_scores', sa.JSON(), nullable=False),
    sa.Column('analysis_summary', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.JSON(), nullable=True),
    sa.Column('decision_makers', sa.JSON(), nullable=True),
    sa.Column('data_sources_used', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_readiness_scores_company_id'), 'ai_readiness_scores', ['company_id'], unique=False)
    op.create_table('tech_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('signal_type', sa.Enum('JOB_POSTING', 'NEWS_MENTION', 'PRESS_RELEASE', 'WEBSITE_CONTENT', 'SOCIAL_MEDIA', name='signaltype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('relevance_score', sa.Integer(), nullable=False),
    sa.Column('ai_mentioned', sa.Integer(), nullable=True),
    sa.Column('tech_keywords', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tech_signals_company_id'), 'tech_signals', ['company_id'], unique=False)
    op.create_index(op.f('ix_tech_signals_signal_type'), 'tech_signals', ['signal_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tech_signals_signal_type'), table_name='tech_signals')
    op.drop_index(op.f('ix_tech_signals_company_id'), table_name='tech_signals')
    op.drop_table('tech_signals')
    op.drop_index(op.f('ix_ai_readiness_scores_company_id'), table_name='ai_readiness_scores')
    op.drop_table('ai_readiness_scores')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_domain'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
